let movies = [
  {
    adult: false,
    backdrop_path: "/y5Z0WesTjvn59jP6yo459eUsbli.jpg",
    genre: "Horror",
    id: 663712,
    original_language: "en",
    original_title: "Terrifier 2",
    overview:
      "After being resurrected by a sinister entity, Art the Clown returns to Miles County where he must hunt down and destroy a teenage girl and her younger brother on Halloween night.  As the body count rises, the siblings fight to stay alive while uncovering the true nature of Art's evil intent.",
    popularity: 7842.699,
    poster_path: "/b6IRp6Pl2Fsq37r9jFhGoLtaqHm.jpg",
    release_date: "2022-10-06",
    title: "Terrifier 2",
    video: false,
    vote_average: 7.1,
    vote_count: 341,
  },
  {
    adult: false,
    backdrop_path: "/bQXAqRx2Fgc46uCVWgoPz5L5Dtr.jpg",
    genre: "Action",
    id: 436270,
    original_language: "en",
    original_title: "Black Adam",
    overview:
      "Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.",
    popularity: 4085.77,
    poster_path: "/3zXceNTtyj5FLjwQXuPvLYK5YYL.jpg",
    release_date: "2022-10-19",
    title: "Black Adam",
    video: false,
    vote_average: 7,
    vote_count: 784,
  },
  {
    adult: false,
    backdrop_path: "/askg3SMvhqEl4OL52YuvdtY40Yb.jpg",
    genre: "Family",
    id: 354912,
    original_language: "en",
    original_title: "Coco",
    overview:
      "Despite his family’s baffling generations-old ban on music, Miguel dreams of becoming an accomplished musician like his idol, Ernesto de la Cruz. Desperate to prove his talent, Miguel finds himself in the stunning and colorful Land of the Dead following a mysterious chain of events. Along the way, he meets charming trickster Hector, and together, they set off on an extraordinary journey to unlock the real story behind Miguel's family history.",
    popularity: 3795.511,
    poster_path: "/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg",
    release_date: "2017-10-27",
    title: "Coco",
    video: false,
    vote_average: 8.2,
    vote_count: 16392,
  },
  {
    adult: false,
    backdrop_path: "/naNXYdBzTEb1KwOdi1RbBkM9Zv1.jpg",
    genre: "Horror",
    id: 420634,
    original_language: "en",
    original_title: "Terrifier",
    overview:
      "On Halloween night, a young woman finds herself as the obsession of a sadistic murderer known as Art the Clown.",
    popularity: 2469.321,
    poster_path: "/6PQqC4SbY910VvyVad6mvsboILU.jpg",
    release_date: "2016-10-15",
    title: "Terrifier",
    video: false,
    vote_average: 6.5,
    vote_count: 816,
  },
  {
    adult: false,
    backdrop_path: "/pGx6O6IwqADOsgmqWzPysmWnOyr.jpg",
    genre: "Action",
    id: 732459,
    original_language: "en",
    original_title: "Blade of the 47 Ronin",
    overview:
      "In this sequel to 47 Ronin, a new class of warriors emerges among the Samurai clans to keep a sought-after sword from falling into the wrong hands.",
    popularity: 2396.57,
    poster_path: "/kjFDIlUCJkcpFxYKtE6OsGcAfQQ.jpg",
    release_date: "2022-10-25",
    title: "Blade of the 47 Ronin",
    video: false,
    vote_average: 7.2,
    vote_count: 33,
  },
  {
    adult: false,
    backdrop_path: "/tIX6j3NzadlwGcJ52nuWdmtOQkg.jpg",
    genre: "Horror",
    id: 717728,
    original_language: "en",
    original_title: "Jeepers Creepers: Reborn",
    overview:
      "Forced to travel with her boyfriend to a horror festival, Laine begins to experience disturbing visions associated with the urban legend of The Creeper. As the festival arrives and the blood-soaked entertainment builds to a frenzy, she becomes the center of it while something unearthly has been summoned.",
    popularity: 2156.734,
    poster_path: "/aGBuiirBIQ7o64FmJxO53eYDuro.jpg",
    release_date: "2022-09-15",
    title: "Jeepers Creepers: Reborn",
    video: false,
    vote_average: 5.7,
    vote_count: 409,
  },
  {
    adult: false,
    backdrop_path: "/iS9U3VHpPEjTWnwmW56CrBlpgLj.jpg",
    genre: "Fantasy",
    id: 642885,
    original_language: "en",
    original_title: "Hocus Pocus 2",
    overview:
      "29 years since the Black Flame Candle was last lit, the 17th-century Sanderson sisters are resurrected, and they are looking for revenge. Now it's up to three high school students to stop the ravenous witches from wreaking a new kind of havoc on Salem before dawn on All Hallow's Eve.",
    popularity: 1966.006,
    poster_path: "/7ze7YNmUaX81ufctGqt0AgHxRtL.jpg",
    release_date: "2022-09-27",
    title: "Hocus Pocus 2",
    video: false,
    vote_average: 7.6,
    vote_count: 999,
  },
  {
    adult: false,
    backdrop_path: "/1DBDwevWS8OhiT3wqqlW7KGPd6m.jpg",
    genre: "Thriller",
    id: 985939,
    original_language: "en",
    original_title: "Fall",
    overview:
      "For best friends Becky and Hunter, life is all about conquering fears and pushing limits. But after they climb 2,000 feet to the top of a remote, abandoned radio tower, they find themselves stranded with no way down. Now Becky and Hunter’s expert climbing skills will be put to the ultimate test as they desperately fight to survive the elements, a lack of supplies, and vertigo-inducing heights",
    popularity: 1888.082,
    poster_path: "/spCAxD99U1A6jsiePFoqdEcY0dG.jpg",
    release_date: "2022-08-11",
    title: "Fall",
    video: false,
    vote_average: 7.3,
    vote_count: 1616,
  },
  {
    adult: false,
    backdrop_path: "/etP5jwlwvkNhwe7jnI2AyA6ZKrR.jpg",
    genre: "Science Fiction",
    id: 575322,
    original_language: "en",
    original_title: "Звёздный разум",
    overview:
      "After depleting Earth's resources for centuries, humankind's survival requires an exodus to outer space. An international expedition is quickly formed to find a suitable new planet, but when plans go awry, the crew is suddenly stranded without power on a strange planet, where something unimaginable lies in wait.",
    popularity: 1846.127,
    poster_path: "/rFljUdOozFEv6HDHIFpFvcYW0ec.jpg",
    release_date: "2022-01-06",
    title: "Project Gemini",
    video: false,
    vote_average: 5.6,
    vote_count: 147,
  },
  {
    adult: false,
    backdrop_path: "/5GA3vV1aWWHTSDO5eno8V5zDo8r.jpg",
    genre: "Horror",
    id: 760161,
    original_language: "en",
    original_title: "Orphan: First Kill",
    overview:
      "After escaping from an Estonian psychiatric facility, Leena Klammer travels to America by impersonating Esther, the missing daughter of a wealthy family. But when her mask starts to slip, she is put against a mother who will protect her family from the murderous “child” at any cost.",
    popularity: 1829.276,
    poster_path: "/pHkKbIRoCe7zIFvqan9LFSaQAde.jpg",
    release_date: "2022-07-27",
    title: "Orphan: First Kill",
    video: false,
    vote_average: 6.8,
    vote_count: 1208,
  },
  {
    adult: false,
    backdrop_path: "/aTovumsNlDjof7YVoU5nW2RHaYn.jpg",
    genre: "Horror",
    id: 616820,
    original_language: "en",
    original_title: "Halloween Ends",
    overview:
      "Four years after the events of Halloween in 2018, Laurie has decided to liberate herself from fear and rage and embrace life. But when a young man is accused of killing a boy he was babysitting, it ignites a cascade of violence and terror that will force Laurie to finally confront the evil she can’t control, once and for all.",
    popularity: 1785.265,
    poster_path: "/h1FGQ6FRW6kNx4ACxjCJ18ssW3Y.jpg",
    release_date: "2022-10-12",
    title: "Halloween Ends",
    video: false,
    vote_average: 6.6,
    vote_count: 820,
  },
  {
    adult: false,
    backdrop_path: "/bJa3RcFKgtVKJqTJCSSuBQeP9c8.jpg",
    genre: "Horror",
    id: 86328,
    original_language: "en",
    original_title: "Terrifier",
    overview:
      "After witnessing a brutal murder on Halloween night, a young woman becomes the next target of a maniacal entity.",
    popularity: 1747.118,
    poster_path: "/gb6rq2nD0jRrN0dCzigg2MxXNsB.jpg",
    release_date: "2011-08-09",
    title: "Terrifier",
    video: false,
    vote_average: 6.8,
    vote_count: 37,
  },
  {
    adult: false,
    backdrop_path: "/5hoS3nEkGGXUfmnu39yw1k52JX5.jpg",
    genre: "Action",
    id: 960704,
    original_language: "ja",
    original_title: "鋼の錬金術師 完結編 最後の錬成",
    overview:
      "The Elric brothers’ long and winding journey comes to a close in this epic finale, where they must face off against an unworldly, nationwide threat.",
    popularity: 1733.109,
    poster_path: "/AeyiuQUUs78bPkz18FY3AzNFF8b.jpg",
    release_date: "2022-06-24",
    title: "Fullmetal Alchemist: The Final Alchemy",
    video: false,
    vote_average: 6.2,
    vote_count: 110,
  },
  {
    adult: false,
    backdrop_path: "/mMA2YNddowV8MZtxpbn0a7Yilum.jpg",
    genre: "War",
    id: 928123,
    original_language: "zh",
    original_title: "长津湖之水门桥",
    overview:
      "In the follow-up to The Battle At Lake Changjin, brothers Wu Qianli and Wu Wanli undertake a new task for the People's Volunteer Army, defending a bridge part of the American troops' escape route from the advancing Chinese.",
    popularity: 1555.57,
    poster_path: "/ugiL6wIhl1OfPyv1gqLkTe45jLl.jpg",
    release_date: "2022-02-01",
    title: "The Battle at Lake Changjin: Water Gate Bridge",
    video: false,
    vote_average: 6.4,
    vote_count: 23,
  },
  {
    adult: false,
    backdrop_path: "/zt6sKnx9dEiRCb7oVMlfmmMGJMO.jpg",
    genre: "Action",
    id: 718930,
    original_language: "en",
    original_title: "Bullet Train",
    overview:
      "Unlucky assassin Ladybug is determined to do his job peacefully after one too many gigs gone off the rails. Fate, however, may have other plans, as Ladybug's latest mission puts him on a collision course with lethal adversaries from around the globe—all with connected, yet conflicting, objectives—on the world's fastest train.",
    popularity: 1553.297,
    poster_path: "/tVxDe01Zy3kZqaZRNiXFGDICdZk.jpg",
    release_date: "2022-07-03",
    title: "Bullet Train",
    video: false,
    vote_average: 7.5,
    vote_count: 2142,
  },
  {
    adult: false,
    backdrop_path: "/nnUQqlVZeEGuCRx8SaoCU4XVHJN.jpg",
    genre: "Fantasy",
    id: 532639,
    original_language: "en",
    original_title: "Pinocchio",
    overview:
      "A wooden puppet embarks on a thrilling adventure to become a real boy.",
    popularity: 1495.034,
    poster_path: "/g8sclIV4gj1TZqUpnL82hKOTK3B.jpg",
    release_date: "2022-09-07",
    title: "Pinocchio",
    video: false,
    vote_average: 6.7,
    vote_count: 1005,
  },
  {
    adult: false,
    backdrop_path: "/tSxbUnrnWlR5dQvUgqMI7sACmFD.jpg",
    genre: "Fantasy",
    id: 779782,
    original_language: "en",
    original_title: "The School for Good and Evil",
    overview:
      "Best friends Sophie and Agatha navigate an enchanted school for young heroes and villains — and find themselves on opposing sides of the battle between good and evil.",
    popularity: 1452.606,
    poster_path: "/6oZeEu1GDILdwezmZ5e2xWISf1C.jpg",
    release_date: "2022-10-19",
    title: "The School for Good and Evil",
    video: false,
    vote_average: 7.3,
    vote_count: 447,
  },
  {
    adult: false,
    backdrop_path: "/2iGUavwv86Hubv3V5Iq4qEQXDfE.jpg",
    genre: "Drama",
    id: 848058,
    original_language: "es",
    original_title: "Cerdita",
    overview:
      "A bullied overweight teenager sees a glimpse of hope when her tormentors are brutally abducted by a mesmerizing stranger.",
    popularity: 1443.877,
    poster_path: "/8EIQAvJjXdbNDMmBtHtgGqbc09V.jpg",
    release_date: "2022-10-07",
    title: "Piggy",
    video: false,
    vote_average: 6.8,
    vote_count: 152,
  },
  {
    adult: false,
    backdrop_path: "/ttkibtcAjoilW1PbTIFy9U9YOdB.jpg",
    genre: "Thriller",
    id: 916719,
    original_language: "en",
    original_title: "Code Name Banshee",
    overview:
      "Caleb, a former government assassin in hiding, who resurfaces when his protégé, the equally deadly killer known as Banshee, discovers a bounty has been placed on Caleb's head.",
    popularity: 1435.273,
    poster_path: "/g29dShv0wHJUvif2KPq039imds5.jpg",
    release_date: "2022-07-01",
    title: "Code Name Banshee",
    video: false,
    vote_average: 4.8,
    vote_count: 40,
  },
  {
    adult: false,
    backdrop_path: "/60UN7vvcWWggLe0Uz9EFZJx718P.jpg",
    genre: "Thriller",
    id: 879538,
    original_language: "en",
    original_title: "Crawlspace",
    overview:
      "After witnessing a brutal murder in a cabin, a man hides in a crawlspace while the killers scour the property for a hidden fortune. As they draw nearer, he must decide if the crawlspace will be his tomb or the battleground in his fight for survival.",
    popularity: 1357.829,
    poster_path: "/qEu6qI5sVoIe10gD1BQBqxcNIW2.jpg",
    release_date: "2022-03-31",
    title: "Crawlspace",
    video: false,
    vote_average: 7.1,
    vote_count: 61,
  },
  {
    adult: false,
    backdrop_path: "/aIkG2V4UXrfkxMdJZmq30xO0QQr.jpg",
    genre: "Science Fiction",
    id: 791155,
    original_language: "en",
    original_title: "Secret Headquarters",
    overview:
      "While hanging out after school, Charlie and his friends discover the headquarters of the world’s most powerful superhero hidden beneath his home. When villains attack, they must team up to defend the headquarters and save the world.",
    popularity: 1272.407,
    poster_path: "/8PsHogUfvjWPGdWAI5uslDhHDx7.jpg",
    release_date: "2022-08-12",
    title: "Secret Headquarters",
    video: false,
    vote_average: 6.9,
    vote_count: 142,
  },
  {
    adult: false,
    backdrop_path: "/jsoz1HlxczSuTx0mDl2h0lxy36l.jpg",
    genre: "Fantasy",
    id: 616037,
    original_language: "en",
    original_title: "Thor: Love and Thunder",
    overview:
      "After his retirement is interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods, Thor Odinson enlists the help of King Valkyrie, Korg, and ex-girlfriend Jane Foster, who now wields Mjolnir as the Mighty Thor. Together they embark upon a harrowing cosmic adventure to uncover the mystery of the God Butcher’s vengeance and stop him before it’s too late.",
    popularity: 1271.517,
    poster_path: "/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg",
    release_date: "2022-07-06",
    title: "Thor: Love and Thunder",
    video: false,
    vote_average: 6.7,
    vote_count: 4484,
  },
  {
    adult: false,
    backdrop_path: "/u6WzMRpTkGzIlfsPNtDfIBfEy9z.jpg",
    genre: "Crime",
    id: 848791,
    original_language: "en",
    original_title: "The Stranger",
    overview:
      "Two strangers strike up a conversation on a long journey. One is a suspect in an unsolved missing person’s case and the other an undercover operative on his trail. Their uneasy friendship becomes the core of this tightly wrought thriller, which is based on the true story of one of the largest investigations and undercover operations in Australia.",
    popularity: 1238.783,
    poster_path: "/ydbm5Ad1nyZq7eywWsw82Wxdsgg.jpg",
    release_date: "2022-10-06",
    title: "The Stranger",
    video: false,
    vote_average: 6.1,
    vote_count: 79,
  },
  {
    adult: false,
    backdrop_path: "/ghsPsvM0sEztdNT4kUlTsBF2LEF.jpg",
    genre: "Drama",
    id: 852046,
    original_language: "fr",
    original_title: "Athena",
    overview:
      "Hours after the tragic death of their youngest brother in unexplained circumstances, three siblings have their lives thrown into chaos.",
    popularity: 1188.867,
    poster_path: "/fenNPxVF5ERy0CSyVruuEg959Hg.jpg",
    release_date: "2022-09-09",
    title: "Athena",
    video: false,
    vote_average: 6.6,
    vote_count: 322,
  },
  {
    adult: false,
    backdrop_path: "/3G8xATwPSnkvkxFGquKnG2xobp7.jpg",
    genre: "Crime",
    id: 884363,
    original_language: "es",
    original_title: "Togo",
    overview:
      "Togo just wants to watch his neighbors' homes, wash their cars and clean up their sidewalks. But the drug traffickers want more from him.",
    popularity: 1115.432,
    poster_path: "/5YZ8JKV8i437z6O4YQ2IEzcSlsD.jpg",
    release_date: "2022-10-05",
    title: "Togo",
    video: false,
    vote_average: 6.4,
    vote_count: 49,
  },
  {
    adult: false,
    backdrop_path: "/7AiIrnDMaOhPrw9elJ5NNjijTW4.jpg",
    genre: "Thriller",
    id: 916605,
    original_language: "en",
    original_title: "The Infernal Machine",
    overview:
      "Reclusive and controversial author Bruce Cogburn is drawn out of hiding by an obsessive fan, forcing the novelist to confront a past that he thought he could escape, and to account for events set in motion by his bestseller decades earlier. Cogburn's search for who is behind the manipulation and mental torment he encounters leads to an emotional roller-coaster ride full of fear and danger, where things are not always as clear as they seem to be, and where past deeds can have dire consequences.",
    popularity: 1064.014,
    poster_path: "/bSqpOGzaKBdGkBLmcm1JJIVryYy.jpg",
    release_date: "2022-09-23",
    title: "The Infernal Machine",
    video: false,
    vote_average: 6.9,
    vote_count: 113,
  },
  {
    adult: false,
    backdrop_path: "/7ZO9yoEU2fAHKhmJWfAc2QIPWJg.jpg",
    genre: "Thriller",
    id: 766507,
    original_language: "en",
    original_title: "Prey",
    overview:
      "When danger threatens her camp, the fierce and highly skilled Comanche warrior Naru sets out to protect her people. But the prey she stalks turns out to be a highly evolved alien predator with a technically advanced arsenal.",
    popularity: 1035.77,
    poster_path: "/ujr5pztc1oitbe7ViMUOilFaJ7s.jpg",
    release_date: "2022-08-05",
    title: "Prey",
    video: false,
    vote_average: 7.9,
    vote_count: 4481,
  },
  {
    adult: false,
    backdrop_path: "/3PieOs1t6dPHWlgvX3XoqTIQLqN.jpg",
    genre: "Adventure",
    id: 507086,
    original_language: "en",
    original_title: "Jurassic World Dominion",
    overview:
      "Four years after the destruction of Isla Nublar, Biosyn operatives attempt to track down Maisie Lockwood, while Dr Ellie Sattler investigates a genetically engineered swarm of giant insects.",
    popularity: 1022.649,
    poster_path: "/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg",
    release_date: "2022-06-01",
    title: "Jurassic World Dominion",
    video: false,
    vote_average: 7,
    vote_count: 3764,
  },
  {
    adult: false,
    backdrop_path: "/olPXihyFeeNvnaD6IOBltgIV1FU.jpg",
    genre: "Horror",
    id: 882598,
    original_language: "en",
    original_title: "Smile",
    overview:
      "After witnessing a bizarre, traumatic incident involving a patient, Dr. Rose Cotter starts experiencing frightening occurrences that she can't explain. As an overwhelming terror begins taking over her life, Rose must confront her troubling past in order to survive and escape her horrifying new reality.",
    popularity: 1009.661,
    poster_path: "/aPqcQwu4VGEewPhagWNncDbJ9Xp.jpg",
    release_date: "2022-09-23",
    title: "Smile",
    video: false,
    vote_average: 6.7,
    vote_count: 351,
  },
  {
    adult: false,
    backdrop_path: "/mjV9gpXO2R2SOYI4ChJZiu6F1OE.jpg",
    genre: "Action",
    id: 759507,
    original_language: "en",
    original_title: "Blackout",
    overview:
      "A man wakes in a hospital with no memory, and quickly finds himself on the run in a locked down hospital with the Cartel on his tail.",
    popularity: 988.136,
    poster_path: "/xDgnmbdWS59NtTPdzujdZGuPUPZ.jpg",
    release_date: "2022-10-12",
    title: "Blackout",
    video: false,
    vote_average: 5.7,
    vote_count: 71,
  },
  {
    adult: false,
    backdrop_path: "/2SEGjVLy7fYbovIyDR7IntH1jT2.jpg",
    genre: "Horror",
    id: 913290,
    original_language: "en",
    original_title: "Barbarian",
    overview:
      "In town for a job interview, a young woman arrives at her Airbnb late at night only to find that it has been mistakenly double-booked and a strange man is already staying there. Against her better judgement, she decides to stay the night anyway, but soon discovers that there is much more to be afraid of in the house than the other guest.",
    popularity: 956.065,
    poster_path: "/idT5mnqPcJgSkvpDX7pJffBzdVH.jpg",
    release_date: "2022-09-08",
    title: "Barbarian",
    video: false,
    vote_average: 7,
    vote_count: 467,
  },
  {
    adult: false,
    backdrop_path: "/ugS5FVfCI3RV0ZwZtBV3HAV75OX.jpg",
    genre: "Animation",
    id: 610150,
    original_language: "ja",
    original_title: "ドラゴンボール超 スーパーヒーロー",
    overview:
      "The Red Ribbon Army, an evil organization that was once destroyed by Goku in the past, has been reformed by a group of people who have created new and mightier Androids, Gamma 1 and Gamma 2, and seek vengeance against Goku and his family.",
    popularity: 939.755,
    poster_path: "/rugyJdeoJm7cSJL1q4jBpTNbxyU.jpg",
    release_date: "2022-06-11",
    title: "Dragon Ball Super: Super Hero",
    video: false,
    vote_average: 8,
    vote_count: 1977,
  },
  {
    adult: false,
    backdrop_path: "/odJ4hx6g6vBt4lBWKFD1tI8WS4x.jpg",
    genre: "Action",
    id: 361743,
    original_language: "en",
    original_title: "Top Gun: Maverick",
    overview:
      "After more than thirty years of service as one of the Navy’s top aviators, and dodging the advancement in rank that would ground him, Pete “Maverick” Mitchell finds himself training a detachment of TOP GUN graduates for a specialized mission the likes of which no living pilot has ever seen.",
    popularity: 936.874,
    poster_path: "/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
    release_date: "2022-05-24",
    title: "Top Gun: Maverick",
    video: false,
    vote_average: 8.3,
    vote_count: 4524,
  },
  {
    adult: false,
    backdrop_path: "/rgZ3hdzgMgYgzvBfwNEVW01bpK1.jpg",
    genre: "Action",
    id: 429473,
    original_language: "en",
    original_title: "Lou",
    overview:
      "A young girl is kidnapped during a powerful storm. Her mother joins forces with her mysterious neighbour to set off in pursuit of the kidnapper. Their journey will test their limits and expose the dark secrets of their past.",
    popularity: 910.301,
    poster_path: "/djM2s4wSaATn4jVB33cV05PEbV7.jpg",
    release_date: "2022-09-23",
    title: "Lou",
    video: false,
    vote_average: 6.6,
    vote_count: 332,
  },
  {
    adult: false,
    backdrop_path: "/4O9kFXsBjlxtgzXWHfgMS9CjhbN.jpg",
    genre: "Thriller",
    id: 619730,
    original_language: "en",
    original_title: "Don't Worry Darling",
    overview:
      "Alice and Jack are lucky to be living in the idealized community of Victory, the experimental company town housing the men who work for the top-secret Victory Project and their families. But when cracks in their idyllic life begin to appear, exposing flashes of something much more sinister lurking beneath the attractive façade, Alice can’t help questioning exactly what they’re doing in Victory, and why.",
    popularity: 889.352,
    poster_path: "/9BXYLjXtSipBp2GfAlsri4i8hPC.jpg",
    release_date: "2022-09-21",
    title: "Don't Worry Darling",
    video: false,
    vote_average: 6.9,
    vote_count: 673,
  },
  {
    adult: false,
    backdrop_path: "/vFGDYJZA7NenGR1OaEGz0pKKFEs.jpg",
    genre: "Animation",
    id: 438148,
    original_language: "en",
    original_title: "Minions: The Rise of Gru",
    overview:
      "A fanboy of a supervillain supergroup known as the Vicious 6, Gru hatches a plan to become evil enough to join them, with the backup of his followers, the Minions.",
    popularity: 879.404,
    poster_path: "/wKiOkZTN9lUUUNZLmtnwubZYONg.jpg",
    release_date: "2022-06-29",
    title: "Minions: The Rise of Gru",
    video: false,
    vote_average: 7.5,
    vote_count: 2264,
  },
  {
    adult: false,
    backdrop_path: "/rV0xrSgkOQj2EpiG8n16VHHJeg3.jpg",
    genre: "Drama",
    id: 541134,
    original_language: "en",
    original_title: "The Good Nurse",
    overview:
      "Suspicious that her colleague is responsible for a series of mysterious patient deaths, a nurse risks her own life to uncover the truth in this gripping thriller based on true events.",
    popularity: 564.564,
    poster_path: "/rSq6cq0LCcbro10jbEaPTEb3WmW.jpg",
    release_date: "2022-10-19",
    title: "The Good Nurse",
    video: false,
    vote_average: 7.2,
    vote_count: 289,
  },
  {
    adult: false,
    backdrop_path: "/hwUxHPkuUleJeoick4uZsrKDXxF.jpg",
    genre: "Animation",
    id: 718789,
    original_language: "en",
    original_title: "Lightyear",
    overview:
      "Legendary Space Ranger Buzz Lightyear embarks on an intergalactic adventure alongside a group of ambitious recruits and his robot companion Sox.",
    popularity: 557.567,
    poster_path: "/65WFr1ZMAbEniIh4jEhbRG9OHHN.jpg",
    release_date: "2022-06-15",
    title: "Lightyear",
    video: false,
    vote_average: 7.2,
    vote_count: 2303,
  },
  {
    adult: false,
    backdrop_path: "/65BCy7SKF2evT9aEPqTgXl9OVLL.jpg",
    genre: "Romance",
    id: 3933,
    original_language: "en",
    original_title: "Corpse Bride",
    overview:
      "Set in a 19th-century European village, this stop-motion animation feature follows the story of Victor, a young man whisked away to the underworld and wed to a mysterious corpse bride, while his real bride Victoria waits bereft in the land of the living.",
    popularity: 557.491,
    poster_path: "/isb2Qow76GpqYmsSyfdMfsYAjts.jpg",
    release_date: "2005-09-12",
    title: "Corpse Bride",
    video: false,
    vote_average: 7.5,
    vote_count: 7558,
  },
  {
    adult: false,
    backdrop_path: "/fOy2Jurz9k6RnJnMUMRDAgBwru2.jpg",
    genre: "Animation",
    id: 508947,
    original_language: "en",
    original_title: "Turning Red",
    overview:
      "Thirteen-year-old Mei is experiencing the awkwardness of being a teenager with a twist – when she gets too excited, she transforms into a giant red panda.",
    popularity: 552.882,
    poster_path: "/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg",
    release_date: "2022-03-01",
    title: "Turning Red",
    video: false,
    vote_average: 7.5,
    vote_count: 3486,
  },
  {
    adult: false,
    backdrop_path: "/3G1Q5xF40HkUBJXxt2DQgQzKTp5.jpg",
    genre: "Animation",
    id: 568124,
    original_language: "en",
    original_title: "Encanto",
    overview:
      "The tale of an extraordinary family, the Madrigals, who live hidden in the mountains of Colombia, in a magical house, in a vibrant town, in a wondrous, charmed place called an Encanto. The magic of the Encanto has blessed every child in the family—every child except one, Mirabel. But when she discovers that the magic surrounding the Encanto is in danger, Mirabel decides that she, the only ordinary Madrigal, might just be her exceptional family's last hope.",
    popularity: 552.223,
    poster_path: "/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg",
    release_date: "2021-10-13",
    title: "Encanto",
    video: false,
    vote_average: 7.7,
    vote_count: 7520,
  },
  {
    adult: false,
    backdrop_path: "/c50IOgYiPH0HSJMiVYjniOyY09U.jpg",
    genre: "Comedy",
    id: 931925,
    original_language: "es",
    original_title: "El gerente",
    overview:
      "Álvaro is a marketing manager, divorced with a son who he can barely talk to, living a mediocre life and doing a mediocre job, until his bosses tell him he needs to improve his marketing campaigns for the next 2018's World Cup. He'll soon launch a plan with Argentina's National Football Team and the upcoming qualifiers that may become a lot more risky that he planned.",
    popularity: 505.649,
    poster_path: "/oOYHNkJ73DDhVTH3qF8YeKp9dcW.jpg",
    release_date: "2022-10-20",
    title: "El gerente",
    video: false,
    vote_average: 8.5,
    vote_count: 32,
  },
  {
    adult: false,
    backdrop_path: "/6AxdvA5hiBGF5ajSKsyt0q7rHei.jpg",
    genre: "Action",
    id: 921360,
    original_language: "en",
    original_title: "Wire Room",
    overview:
      "New recruit Justin Rosa must monitor arms-smuggling cartel member Eddie Flynn — and keep him alive at all costs. When a SWAT team descends on Flynn’s home, Rosa breaks protocol and contacts the gangster directly to save his life. As gunmen break into the Wire Room and chaos erupts, Mueller and Rosa make a final, desperate stand against the corrupt agents and officials who seek to destroy evidence and kill them both.",
    popularity: 493.036,
    poster_path: "/b9ykj4v8ykjRoGB7SpI1OuxblNU.jpg",
    release_date: "2022-09-02",
    title: "Wire Room",
    video: false,
    vote_average: 6.9,
    vote_count: 99,
  },
  {
    adult: false,
    backdrop_path: "/yaze6df9AMIA9oeDEbIZ4zOTRCJ.jpg",
    genre: "Fantasy",
    id: 960700,
    original_language: "ja",
    original_title: "鋼の錬金術師 完結編 復讐者スカー",
    overview:
      "The Elric brothers meet their toughest opponent yet — a lone serial killer with a large scar on his forehead.",
    popularity: 480.92,
    poster_path: "/c5OwwBNyJkwyroIOIJL9IiRjydR.jpg",
    release_date: "2022-05-20",
    title: "Fullmetal Alchemist: The Revenge of Scar",
    video: false,
    vote_average: 7,
    vote_count: 132,
  },
  {
    adult: false,
    backdrop_path: "/zldQJ1EhIc7G79cYyXrzQQzUl7a.jpg",
    genre: "Animation",
    id: 43641,
    original_language: "en",
    original_title: "Superman/Shazam!: The Return of Black Adam",
    overview:
      "Chosen the world’s protector against the Seven Deadly Enemies of Man – pride, envy, greed, hatred, selfishness, laziness and injustice – young Billy Batson accepts his destiny as Captain Marvel. Battling alongside Superman against nefarious Black Adam, Billy soon discovers the challenge super heroes ultimately face: is it revenge or justice?",
    popularity: 479.74,
    poster_path: "/3MgwChvi42N1RnhQE9A4pQVHyUY.jpg",
    release_date: "2010-11-16",
    title: "Superman/Shazam!: The Return of Black Adam",
    video: false,
    vote_average: 7.2,
    vote_count: 911,
  },
  {
    adult: false,
    backdrop_path: "/A2XhlMUimRDViZDuJPeDtaJoHmT.jpg",
    genre: "Animation",
    id: 1015602,
    original_language: "en",
    original_title: "Welcome to the Club",
    overview:
      "Heart set on becoming a princess, Lisa Simpson is surprised to learn being bad might be more fun.",
    popularity: 478.783,
    poster_path: "/kxB9E6fo0ycHzd13oOTHmGa5Njd.jpg",
    release_date: "2022-09-08",
    title: "Welcome to the Club",
    video: false,
    vote_average: 6.7,
    vote_count: 110,
  },
  {
    adult: false,
    backdrop_path: "/ru5zAV1Ij6bQGedBkczqhiBmjzn.jpg",
    genre: "Drama",
    id: 1029446,
    original_language: "tl",
    original_title: "Selina's Gold",
    overview:
      "Selina's father sells her to Tiago who makes her a sex slave. With the help of Domeng, Tiago's blind slave, she plans their way out of this living hell.",
    popularity: 472.537,
    poster_path: "/4IVBk5IpiPvkBHpOQTwhb4qlQ4t.jpg",
    release_date: "2022-10-24",
    title: "Selina's Gold",
    video: false,
    vote_average: 2,
    vote_count: 1,
  },
  {
    adult: false,
    backdrop_path: "/m3Ys7UDzUzOyoPYKzp4GhKKokUr.jpg",
    genre: "Animation",
    id: 585083,
    original_language: "en",
    original_title: "Hotel Transylvania: Transformania",
    overview:
      "When Van Helsing's mysterious invention, the Monsterfication Ray, goes haywire, Drac and his monster pals are all transformed into humans, and Johnny becomes a monster. In their new mismatched bodies, Drac and Johnny must team up and race across the globe to find a cure before it's too late, and before they drive each other crazy.",
    popularity: 470.393,
    poster_path: "/teCy1egGQa0y8ULJvlrDHQKnxBL.jpg",
    release_date: "2022-02-25",
    title: "Hotel Transylvania: Transformania",
    video: false,
    vote_average: 7.1,
    vote_count: 1255,
  },
  {
    adult: false,
    backdrop_path: "/xHRabofjmMGoIV3mb6xgy4nwOcS.jpg",
    genre: "Horror",
    id: 801071,
    original_language: "en",
    original_title: "The Jack in the Box: Awakening",
    overview:
      "When a vintage Jack-in-the-box is opened by a dying woman, she enters into a deal with the demon within that would see her illness cured in return for helping it claim six innocent victims.",
    popularity: 469.889,
    poster_path: "/3Ib8vlWTrAKRrTWUrTrZPOMW4jp.jpg",
    release_date: "2022-02-24",
    title: "The Jack in the Box: Awakening",
    video: false,
    vote_average: 6.4,
    vote_count: 184,
  },
  {
    adult: false,
    backdrop_path: "/54PmeEzQMvpojpJBku61ZGQnWUX.jpg",
    genre: "Animation",
    id: 900667,
    original_language: "ja",
    original_title: "ONE PIECE FILM RED",
    overview:
      "Uta — the most beloved singer in the world. Her voice, which she sings with while concealing her true identity, has been described as “otherworldly.” She will appear in public for the first time at a live concert. As the venue fills with all kinds of Uta fans — excited pirates, the Navy watching closely, and the Straw Hats led by Luffy who simply came to enjoy her sonorous performance — the voice that the whole world has been waiting for is about to resound.",
    popularity: 465.534,
    poster_path: "/m80kPdrmmtEh9wlLroCp0bwUGH0.jpg",
    release_date: "2022-08-06",
    title: "One Piece Film Red",
    video: false,
    vote_average: 7.4,
    vote_count: 119,
  },
  {
    adult: false,
    backdrop_path: "/8moTOzunF7p40oR5XhlDvJckOSW.jpg",
    genre: "Horror",
    id: 474350,
    original_language: "en",
    original_title: "It Chapter Two",
    overview:
      "27 years after overcoming the malevolent supernatural entity Pennywise, the former members of the Losers' Club, who have grown up and moved away from Derry, are brought back together by a devastating phone call.",
    popularity: 451.306,
    poster_path: "/zfE0R94v1E8cuKAerbskfD3VfUt.jpg",
    release_date: "2019-09-04",
    title: "It Chapter Two",
    video: false,
    vote_average: 6.9,
    vote_count: 7300,
  },
  {
    adult: false,
    backdrop_path: "/1Ds7xy7ILo8u2WWxdnkJth1jQVT.jpg",
    genre: "Action",
    id: 752623,
    original_language: "en",
    original_title: "The Lost City",
    overview:
      "Reclusive author Loretta Sage writes about exotic places in her popular adventure novels that feature a handsome cover model named Alan. While on tour promoting her new book with Alan, Loretta gets kidnapped by an eccentric billionaire who hopes she can lead him to the ancient city's lost treasure that featured in her latest story. Alan, determined to prove he can be a hero in real life and not just on the pages of her books, sets off to rescue her.",
    popularity: 445.583,
    poster_path: "/neMZH82Stu91d3iqvLdNQfqPPyl.jpg",
    release_date: "2022-03-24",
    title: "The Lost City",
    video: false,
    vote_average: 6.8,
    vote_count: 2137,
  },
  {
    adult: false,
    backdrop_path: "/mqsPyyeDCBAghXyjbw4TfEYwljw.jpg",
    genre: "Action",
    id: 49046,
    original_language: "de",
    original_title: "Im Westen nichts Neues",
    overview:
      "Paul Baumer and his friends Albert and Muller, egged on by romantic dreams of heroism, voluntarily enlist in the German army. Full of excitement and patriotic fervour, the boys enthusiastically march into a war they believe in. But once on the Western Front, they discover the soul-destroying horror of World War I.",
    popularity: 440.181,
    poster_path: "/2IRjbi9cADuDMKmHdLK7LaqQDKA.jpg",
    release_date: "2022-10-07",
    title: "All Quiet on the Western Front",
    video: false,
    vote_average: 7.9,
    vote_count: 336,
  },
  {
    adult: false,
    backdrop_path: "/tviTAFuCFRLElylvBAMPjdRnCDZ.jpg",
    genre: "Thriller",
    id: 999205,
    original_language: "en",
    original_title: "Stowaway",
    overview:
      "A tenacious party girl fights to survive after three thieves commandeer her luxury yacht. Unable to escape and trapped on the yacht at high seas, the prey becomes the hunter as she turns the tables on the intruders and takes matters into her own hands.",
    popularity: 432.594,
    poster_path: "/1RmugOkBFU5eXu1dbr1zdxChLfQ.jpg",
    release_date: "2022-08-31",
    title: "Stowaway",
    video: false,
    vote_average: 6.9,
    vote_count: 39,
  },
  {
    adult: false,
    backdrop_path: "/rHzoz94bRfyfNLjiIB26Wt5KDHE.jpg",
    genre: "Action",
    id: 773867,
    original_language: "ko",
    original_title: "서울대작전",
    overview:
      "Chasing speed, dreams and money, a team of drivers get involved in the slush fund investigation of a powerful figure during the 1988 Seoul Olympics.",
    popularity: 426.767,
    poster_path: "/txaOvJ6HURmqFbpVtJezWNWqaR4.jpg",
    release_date: "2022-08-26",
    title: "Seoul Vibe",
    video: false,
    vote_average: 6.9,
    vote_count: 97,
  },
  {
    adult: false,
    backdrop_path: "/7zQJYV02yehWrQN6NjKsBorqUUS.jpg",
    genre: "Action",
    id: 724495,
    original_language: "en",
    original_title: "The Woman King",
    overview:
      "The story of the Agojie, the all-female unit of warriors who protected the African Kingdom of Dahomey in the 1800s with skills and a fierceness unlike anything the world has ever seen, and General Nanisca as she trains the next generation of recruits and readies them for battle against an enemy determined to destroy their way of life.",
    popularity: 420.105,
    poster_path: "/438QXt1E3WJWb3PqNniK0tAE5c1.jpg",
    release_date: "2022-09-15",
    title: "The Woman King",
    video: false,
    vote_average: 7.4,
    vote_count: 198,
  },
  {
    adult: false,
    backdrop_path: "/l0ig2COvaUgJce3zQvxtFSSO7r7.jpg",
    genre: "Mystery",
    id: 484907,
    original_language: "en",
    original_title: "Homebound",
    overview:
      "A young woman arrives at the home of her new husband's estranged family to find the children behaving in increasingly unnerving ways.",
    popularity: 418.544,
    poster_path: "/kgaadQfeX9yi30oBCreM7cxurqj.jpg",
    release_date: "2022-04-01",
    title: "Homebound",
    video: false,
    vote_average: 3.7,
    vote_count: 6,
  },
  {
    adult: false,
    backdrop_path: "/z8KsgBFtduX5bS1yVkjoGo4L7KJ.jpg",
    genre: "Drama",
    id: 597922,
    original_language: "en",
    original_title: "The Greatest Beer Run Ever",
    overview:
      "Chickie wants to support his friends fighting in Vietnam, so he does something wild—personally bring them American beer. What starts as a well-meaning journey quickly changes Chickie’s life and perspective. Based on a true story.",
    popularity: 418.484,
    poster_path: "/ggf37TpcKaxwguhvtNn6MQpyqBn.jpg",
    release_date: "2022-09-30",
    title: "The Greatest Beer Run Ever",
    video: false,
    vote_average: 7.9,
    vote_count: 304,
  },
  {
    adult: false,
    backdrop_path: "/cugmVwK0N4aAcLibelKN5jWDXSx.jpg",
    genre: "Animation",
    id: 768744,
    original_language: "ja",
    original_title:
      "僕のヒーローアカデミア THE MOVIE ワールド ヒーローズ ミッション",
    overview:
      "A mysterious group called Humarize strongly believes in the Quirk Singularity Doomsday theory which states that when quirks get mixed further in with future generations, that power will bring forth the end of humanity. In order to save everyone, the Pro-Heroes around the world ask UA Academy heroes-in-training to assist them and form a world-class selected hero team. It’s up to the heroes to save the world and the future of heroes in what is the most dangerous crisis to take place yet in My Hero Academia.",
    popularity: 415.964,
    poster_path: "/AsTlA7dj2ySGY1pzGSD0MoHFhEF.jpg",
    release_date: "2021-08-06",
    title: "My Hero Academia: World Heroes' Mission",
    video: false,
    vote_average: 7.6,
    vote_count: 313,
  },
  {
    adult: false,
    backdrop_path: "/i9BtOklh2txI78wNSTNjoAZ6Fvj.jpg",
    genre: "Comedy",
    id: 975120,
    original_language: "es",
    original_title: "Padre no hay mas que Uno 3",
    overview:
      "Christmas is coming. The children accidentally break a Nativity scene figurine from their father's collection and must by all means get an equal one, the problem is that it is a unique antique piece. Sara, the eldest daughter breaks up with her boyfriend, Ocho, who will try to recover her favors with the help of her father-in-law, Javier. Precisely Javier's father-in-law, Marisa's father, will be welcomed into the family home to spend the holidays after her recent separation, which will not leave Javier's mother, Milagros, indifferent. Rocío, the folklore of the family, who has been playing the Virgin for several Christmases, is relegated this year to playing the shepherdess, something that her father, Javier, is not willing to assume.",
    popularity: 412.255,
    poster_path: "/k2v9xSPtiyxCNxaRGtj7COwdgG3.jpg",
    release_date: "2022-07-15",
    title: "Father There Is Only One 3",
    video: false,
    vote_average: 7.7,
    vote_count: 144,
  },
  {
    adult: false,
    backdrop_path: "/xXSjMjCdZ6v7NIFvsSMNqe4ySkF.jpg",
    genre: "Horror",
    id: 1032950,
    original_language: "pl",
    original_title: "Ostatnia Wieczerza",
    overview:
      "In a monastery cut off from the world, the monks run a clinic for the possessed. One day, a young policeman Marek comes to the convent. Posing as a clergyman, he penetrates monastic life and tries to explain the recent, mysterious disappearance of several tormented inmates. It turns out, however, that there is no way out of the monastery.",
    popularity: 411.036,
    poster_path: "/y47wBamj9vdqBeGaLEFTrYEPTeC.jpg",
    release_date: "2022-10-26",
    title: "Hellhole",
    video: false,
    vote_average: 6.3,
    vote_count: 71,
  },
  {
    adult: false,
    backdrop_path: "/endVnEgUGjibpLaF0yjUX2CWhh4.jpg",
    genre: "Animation",
    id: 1007401,
    original_language: "en",
    original_title: "Mortal Kombat Legends: Snow Blind",
    overview:
      "Hellbent on taking over Earthrealm, Kano viciously attacks town after town with the aid of three cold-blooded Black Dragon mercenaries. Those who don’t submit are annihilated but one young man won’t bend the knee to Kano: Kenshi.",
    popularity: 406.253,
    poster_path: "/xvjCiv1xNlK1kNnoe1nul899vIp.jpg",
    release_date: "2022-10-09",
    title: "Mortal Kombat Legends: Snow Blind",
    video: false,
    vote_average: 8.1,
    vote_count: 72,
  },
  {
    adult: false,
    backdrop_path: "/b1L7qevxiVpkVFq4dmdQPGFPWH0.jpg",
    genre: "Horror",
    id: 836225,
    original_language: "en",
    original_title: "The Exorcism of God",
    overview:
      "An American priest working in Mexico is considered a saint by many local parishioners. However, due to a botched exorcism, he carries a secret that’s eating him alive until he gets an opportunity to face his demon one final time.",
    popularity: 402.51,
    poster_path: "/9X9wKbF0ED1AQpgIkvq0MG4Y4wi.jpg",
    release_date: "2022-03-11",
    title: "The Exorcism of God",
    video: false,
    vote_average: 7.3,
    vote_count: 676,
  },
  {
    adult: false,
    backdrop_path: "/fuuZFPc8x6gQ8mLGoBp9vrmcQMT.jpg",
    genre: "Horror",
    id: 610253,
    original_language: "en",
    original_title: "Halloween Kills",
    overview:
      "The nightmare isn't over as unstoppable killer Michael Myers escapes from Laurie Strode's trap to continue his ritual bloodbath. Injured and taken to the hospital, Laurie fights through the pain as she inspires residents of Haddonfield, to rise up against Myers. Taking matters into their own hands, the Strode women and other survivors form a vigilante mob to hunt down Michael and end his reign of terror once and for all.",
    popularity: 401.491,
    poster_path: "/ir9eyz1mtgsohjvo7UYtqUfFuES.jpg",
    release_date: "2021-10-14",
    title: "Halloween Kills",
    video: false,
    vote_average: 6.6,
    vote_count: 2038,
  },
  {
    adult: false,
    backdrop_path: "/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg",
    genre: "Adventure",
    id: 299536,
    original_language: "en",
    original_title: "Avengers: Infinity War",
    overview:
      "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.",
    popularity: 397.892,
    poster_path: "/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
    release_date: "2018-04-25",
    title: "Avengers: Infinity War",
    video: false,
    vote_average: 8.3,
    vote_count: 25655,
  },
  {
    adult: false,
    backdrop_path: "/cqnVuxXe6vA7wfNWubak3x36DKJ.jpg",
    genre: "Action",
    id: 639933,
    original_language: "en",
    original_title: "The Northman",
    overview:
      "Prince Amleth is on the verge of becoming a man when his father is brutally murdered by his uncle, who kidnaps the boy's mother. Two decades later, Amleth is now a Viking who's on a mission to save his mother, kill his uncle and avenge his father.",
    popularity: 394.772,
    poster_path: "/zhLKlUaF1SEpO58ppHIAyENkwgw.jpg",
    release_date: "2022-04-07",
    title: "The Northman",
    video: false,
    vote_average: 7.2,
    vote_count: 2605,
  },
  {
    adult: false,
    backdrop_path: "/zGLHX92Gk96O1DJvLil7ObJTbaL.jpg",
    genre: "Fantasy",
    id: 338953,
    original_language: "en",
    original_title: "Fantastic Beasts: The Secrets of Dumbledore",
    overview:
      "Professor Albus Dumbledore knows the powerful, dark wizard Gellert Grindelwald is moving to seize control of the wizarding world. Unable to stop him alone, he entrusts magizoologist Newt Scamander to lead an intrepid team of wizards and witches. They soon encounter an array of old and new beasts as they clash with Grindelwald's growing legion of followers.",
    popularity: 394.51,
    poster_path: "/3c5GNLB4yRSLBby0trHoA1DSQxQ.jpg",
    release_date: "2022-04-06",
    title: "Fantastic Beasts: The Secrets of Dumbledore",
    video: false,
    vote_average: 6.8,
    vote_count: 2910,
  },
  {
    adult: false,
    backdrop_path: "/vIgyYkXkg6NC2whRbYjBD7eb3Er.jpg",
    genre: "Science Fiction",
    id: 580489,
    original_language: "en",
    original_title: "Venom: Let There Be Carnage",
    overview:
      "After finding a host body in investigative reporter Eddie Brock, the alien symbiote must face a new enemy, Carnage, the alter ego of serial killer Cletus Kasady.",
    popularity: 392.654,
    poster_path: "/rjkmN1dniUHVYAtwuV3Tji7FsDO.jpg",
    release_date: "2021-09-30",
    title: "Venom: Let There Be Carnage",
    video: false,
    vote_average: 6.9,
    vote_count: 8164,
  },
  {
    adult: false,
    backdrop_path: "/t4To8feUSysyBs4tlBAbXIrKlCv.jpg",
    genre: "Action",
    id: 860623,
    original_language: "en",
    original_title: "Last Man Down",
    overview:
      "After civilization succumbs to a deadly pandemic and his wife is murdered, a special forces soldier abandons his duty and becomes a hermit in the Nordic wilderness. Years later, a wounded woman appears on his doorstep. She's escaped from a lab and her pursuers believe her blood is the key to a worldwide cure. He's hesitant to get involved, but all doubts are cast aside when he discovers her pursuer is none other than Commander Stone, the man that murdered his wife some years ago.",
    popularity: 391.633,
    poster_path: "/4B7liCxNCZIZGONmAMkCnxVlZQV.jpg",
    release_date: "2022-11-03",
    title: "Last Man Down",
    video: false,
    vote_average: 6.3,
    vote_count: 6,
  },
  {
    adult: false,
    backdrop_path: "/l99dylTOAMkwKSr54X5ytiEtnLA.jpg",
    genre: "Fantasy",
    id: 919355,
    original_language: "en",
    original_title: "Dragon Knight",
    overview:
      "Many years after the war has been lost, and all the dragons slain, a lone knight travels the lands of Agonos seeking to raise an army against the demon lord Abaddon. When a healer's vision reveals that one dragon still lives, and together with an eager young squire, the knight sets off in search of the fabled creature. As the armies of Abaddon descend on the human kingdoms, the dragon is their last hope of fending off the horde, before it lays waste to the lands of men. But does the creature even exist? And if it does, will it fight for them once more?",
    popularity: 387.557,
    poster_path: "/zkGFADykBtfPfTv7YJooxTH52ph.jpg",
    release_date: "2022-03-21",
    title: "Dragon Knight",
    video: false,
    vote_average: 7.1,
    vote_count: 32,
  },
  {
    adult: false,
    backdrop_path: "/ecPB0jEuPGoAL0nH1r0831DUt3r.jpg",
    genre: "Action",
    id: 818397,
    original_language: "en",
    original_title: "Memory",
    overview:
      "Alex, an assassin-for-hire, finds that he's become a target after he refuses to complete a job for a dangerous criminal organization. With the crime syndicate and FBI in hot pursuit, Alex has the skills to stay ahead, except for one thing: he is struggling with severe memory loss, affecting his every move. Alex must question his every action and whom he can ultimately trust.",
    popularity: 386.464,
    poster_path: "/QaNLpq3Wuu2yp5ESsXYcQCOpUk.jpg",
    release_date: "2022-04-28",
    title: "Memory",
    video: false,
    vote_average: 7.1,
    vote_count: 907,
  },
  {
    adult: false,
    backdrop_path: "/cyV2syN5zRQwU6BmWMyMFyjRLow.jpg",
    genre: "Action",
    id: 843633,
    original_language: "en",
    original_title: "White Elephant",
    overview:
      "An ex-marine enforcer must battle his conscience and code of honor when he is forced to do things for the mob.",
    popularity: 385.236,
    poster_path: "/lG56H40Y1BuHSPoWtEgDJsSgDBZ.jpg",
    release_date: "2022-06-03",
    title: "White Elephant",
    video: false,
    vote_average: 6.6,
    vote_count: 85,
  },
  {
    adult: false,
    backdrop_path: "/nlG452icactoT6hbqECbSEVfGII.jpg",
    genre: "Animation",
    id: 228326,
    original_language: "en",
    original_title: "The Book of Life",
    overview:
      "The journey of Manolo, a young man who is torn between fulfilling the expectations of his family and following his heart. Before choosing which path to follow, he embarks on an incredible adventure that spans three fantastical worlds where he must face his greatest fears.",
    popularity: 384.978,
    poster_path: "/aotTZos5KswgCryEzx2rlOjFsm1.jpg",
    release_date: "2014-10-01",
    title: "The Book of Life",
    video: false,
    vote_average: 7.5,
    vote_count: 2274,
  },
  {
    adult: false,
    backdrop_path: "/mYOooABOzWRaFMRWDhUAXiKuTaO.jpg",
    genre: "Thriller",
    id: 831410,
    original_language: "en",
    original_title: "Bring It On: Cheer or Die",
    overview:
      "When a cheer squad practices their routines on Halloween weekend in an abandoned school, they are picked off one by one by an unknown killer.",
    popularity: 380.492,
    poster_path: "/ciRq9QUBpFWNsFKs2opG5tP157.jpg",
    release_date: "2022-09-27",
    title: "Bring It On: Cheer or Die",
    video: false,
    vote_average: 6.5,
    vote_count: 57,
  },
  {
    adult: false,
    backdrop_path: "/pcDc2WJAYGJTTvRSEIpRZwM3Ola.jpg",
    genre: "Action",
    id: 791373,
    original_language: "en",
    original_title: "Zack Snyder's Justice League",
    overview:
      "Determined to ensure Superman's ultimate sacrifice was not in vain, Bruce Wayne aligns forces with Diana Prince with plans to recruit a team of metahumans to protect the world from an approaching threat of catastrophic proportions.",
    popularity: 373.856,
    poster_path: "/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg",
    release_date: "2021-03-18",
    title: "Zack Snyder's Justice League",
    video: false,
    vote_average: 8.2,
    vote_count: 8274,
  },
  {
    adult: false,
    backdrop_path: "/rRpAZOPY3XxMJY65AJ396IWyjU4.jpg",
    genre: "Animation",
    id: 14836,
    original_language: "en",
    original_title: "Coraline",
    overview:
      "When Coraline moves to an old house, she feels bored and neglected by her parents. She finds a hidden door with a bricked up passage. During the night, she crosses the passage and finds a parallel world where everybody has buttons instead of eyes, with caring parents and all her dreams coming true. When the Other Mother invites Coraline to stay in her world forever, the girl refuses and finds that the alternate reality where she is trapped is only a trick to lure her.",
    popularity: 372.54,
    poster_path: "/gPMh5rsVrDDAYMDbTcz6Up1DQ4z.jpg",
    release_date: "2009-02-05",
    title: "Coraline",
    video: false,
    vote_average: 7.8,
    vote_count: 6145,
  },
  {
    adult: false,
    backdrop_path: "/9IDJpHROaC0S1ZlIxrvzOcOX5yC.jpg",
    genre: "Animation",
    id: 629542,
    original_language: "en",
    original_title: "The Bad Guys",
    overview:
      "When the infamous Bad Guys are finally caught after years of countless heists and being the world’s most-wanted villains, Mr. Wolf brokers a deal to save them all from prison.",
    popularity: 367.287,
    poster_path: "/7qop80YfuO0BwJa1uXk1DXUUEwv.jpg",
    release_date: "2022-03-17",
    title: "The Bad Guys",
    video: false,
    vote_average: 7.7,
    vote_count: 1104,
  },
  {
    adult: false,
    backdrop_path: null,
    genre: "Thriller",
    id: 1014226,
    original_language: "es",
    original_title: "Sonríe",
    overview: "",
    popularity: 363.34,
    poster_path: "/wHowKf77gNZbVo9yu5ggiNBFCdJ.jpg",
    release_date: "2022-08-18",
    title: "Sonríe",
    video: false,
    vote_average: 1,
    vote_count: 1,
  },
  {
    adult: false,
    backdrop_path: "/ciKBP3tgzUxp7sHFNZxofBXUS8k.jpg",
    genre: "Horror",
    id: 602223,
    original_language: "en",
    original_title: "The Forever Purge",
    overview:
      "All the rules are broken as a sect of lawless marauders decides that the annual Purge does not stop at daybreak and instead should never end as they chase a group of immigrants who they want to punish because of their harsh historical past.",
    popularity: 360.815,
    poster_path: "/lB068qa6bQ0QKYKyC2xnYGvYjl7.jpg",
    release_date: "2021-06-30",
    title: "The Forever Purge",
    video: false,
    vote_average: 7.1,
    vote_count: 1930,
  },
  {
    adult: false,
    backdrop_path: "/as4jvr6PF7Wfs0RyUl5bOJcB3yt.jpg",
    genre: "Drama",
    id: 626735,
    original_language: "en",
    original_title: "Dog",
    overview:
      "An army ranger and his dog embark on a road trip along the Pacific Coast Highway to attend a friend's funeral.",
    popularity: 353.242,
    poster_path: "/zHQy4h36WwuCetKS7C3wcT1hkgA.jpg",
    release_date: "2022-02-17",
    title: "Dog",
    video: false,
    vote_average: 7.4,
    vote_count: 969,
  },
  {
    adult: false,
    backdrop_path: "/zlLQXKsSa2CEkz3UBFWPUPX90PN.jpg",
    genre: "Thriller",
    id: 968857,
    original_language: "en",
    original_title: "Looks Can Kill",
    overview:
      "A group of models is killed off, one by one, and everyone is a suspect.",
    popularity: 352.592,
    poster_path: "/1uy2PNFwtkqH3mhGd6irk5aeIrF.jpg",
    release_date: "2022-02-01",
    title: "Looks Can Kill",
    video: false,
    vote_average: 5.3,
    vote_count: 8,
  },
  {
    adult: false,
    backdrop_path: "/6cpRpfD3isvluFwXDGSiDVyibPJ.jpg",
    genre: "Romance",
    id: 829560,
    original_language: "pl",
    original_title: "The Next 365 Days",
    overview:
      "Laura and Massimo's relationship hangs in the balance as they try to overcome trust issues while a tenacious Nacho works to push them apart.",
    popularity: 352.452,
    poster_path: "/6FsGeIp7heHm5eh4tIxTzHIRxmt.jpg",
    release_date: "2022-08-19",
    title: "The Next 365 Days",
    video: false,
    vote_average: 6.6,
    vote_count: 547,
  },
  {
    adult: false,
    backdrop_path: "/bL7VIHQ4Nl0hZMw8ZeX6byoEEZJ.jpg",
    genre: "Science Fiction",
    id: 1006851,
    original_language: "en",
    original_title: "Office Invasion",
    overview:
      "Three friends come together to defend their valuable mining company from…aliens?! What could possibly go wrong?",
    popularity: 351.196,
    poster_path: "/khcVwO0gwguC1CndbxtH1bzk4aj.jpg",
    release_date: "2022-08-10",
    title: "Office Invasion",
    video: false,
    vote_average: 5.8,
    vote_count: 88,
  },
  {
    adult: false,
    backdrop_path: "/jzWT0zd8U77fqWg5WgUfYaMzSFz.jpg",
    genre: "Action",
    id: 526896,
    original_language: "en",
    original_title: "Morbius",
    overview:
      "Dangerously ill with a rare blood disorder, and determined to save others suffering his same fate, Dr. Michael Morbius attempts a desperate gamble. What at first appears to be a radical success soon reveals itself to be a remedy potentially worse than the disease.",
    popularity: 350.779,
    poster_path: "/6JjfSchsU6daXk2AKX8EEBjO3Fm.jpg",
    release_date: "2022-03-30",
    title: "Morbius",
    video: false,
    vote_average: 6.3,
    vote_count: 2838,
  },
];

// 1. Buscar la película cuyo id es 843633 y mostrar su nombre por pantalla.
/*let findingMovie = movies.find((pelicula) => pelicula.id === 843633);
if (findingMovie) {
  alert(findingMovie.title);
} else {
  alert("Pelicula no existe");
}*/

// 2. Pedir al usuario un nombre de una película y en caso de que se encuentre en el array movies
// mostrar por pantalla la cantidad de votos que tiene.
/*let movieName = prompt("Ingrese el nombre de una pelicula").toLowerCase();
let findingMovie = movies.find(
  (movie) => movie.title.toLowerCase() === movieName
);
if (findingMovie) {
  alert(findingMovie.vote_count);
} else {
  alert("Pelicula no encontrada");
}*/

// 3. Fitrar las películas más vistas, es decir, las que superan los 1000 puntos de popularidad.

// let popularityMovies = movies.filter((movie) => movie.popularity > 1000);
// alert(listarPeliculasPopulares(popularityMovies));

// function listarPeliculasPopulares(movies) {
//   /*METODO 1*/
//   //   let lista = "";
//   //   for (const movie of movies) {
//   //     lista += movie.id + " - " + movie.title + "\n";
//   //   }
//   //   return lista;
//   /*METODO 2*/
//   //   let lista = ""
//   //   movies.forEach((movie) => (lista += movie.id + " - " + movie.title + "\n"));
//   //   return lista;
//   /*METODO 3*/
//   return movies.map((movie) => movie.id + " - " + movie.title).join("\n");
// }

// 4. Mostrar el nombre de cada película concatenado con la fecha en que salió.

let popularityMovies = movies.filter((movie) => movie.popularity > 1000);
alert(listarPeliculasPopulares(popularityMovies, "title", "release_date"));

function listarPeliculasPopulares(movies, prop1, prop2) {
  return movies.map((movie) => movie[prop1] + " - " + movie[prop2]).join("\n");
}

// 5. Ordenar las películas por popularidad de manera ascendente.
ordenar(movies, "popularity", true);
alert(listarPeliculasPopulares(movies, "title", "popularity"));
// 6. Ordenar las películas por popularidad de manera descendente.
ordenar(movies, "popularity", false);
alert(listarPeliculasPopulares(movies, "title", "popularity"));

function ordenar(movies, propiedad, esAscendente) {
  movies.sort((a, b) => {
    if (a[propiedad] < b[propiedad]) {
      return -1;
    }
    if (a[propiedad] > b[propiedad]) {
      return 1;
    }
    return 0;
  });
  if (!esAscendente) {
    movies.reverse();
  }
}

// 7. Ordenar las películas por nombre de manera ascendente.
// ordenar(movies, "title", true);
// alert(listarPeliculasPopulares(movies, "id", "title"));

// 8. Ordenar las películas por nombre de manera descendente.
// ordenar(movies, "title", false);
// alert(listarPeliculasPopulares(movies, "id", "title"));

// 9. El array contiene mucha información que no uso en mi web por lo tanto quiero guardar en
// un nuevo array sólo el nombre, id y popularidad de cada una de las películas.
let peliculasResumidas = movies.map((movie) => {
  return {
    id: movie.id,
    nombre: movie.title,
    popularidad: movie.popularity,
  };
});
console.log(peliculasResumidas);
// 10. Tomando el nuevo array del ejercicio 9, agregale a cada película la propiedad views con
// valor 0 además de las que tenemos actualmente (nombre, id y popularidad)

peliculasResumidas.forEach((movie) => (movie.vistas = 0));
console.log(peliculasResumidas);

// 11. Trabajando sobre el mismo array del ejercicio 9 y 10, me di cuenta que perdí la propiedad
// adult, ahora deseo crear un nuevo array agregando la propiedad “adult” con valor true si el
// género es “Horror” o “Thriller” sino false. Las demás propiedades quedan tal cual están, es
// decir, me quedaría nombre, id, popularidad, views y adult.
peliculasResumidas.forEach((movie) => {
  let peliculaOriginal = movies.find((peliOrig) => peliOrig.id === movie.id);

  movie.paraAdultos =
    peliculaOriginal.genre === "Horror" ||
    peliculaOriginal.genre === "Thriller";
  //   if (
  //     peliculaOriginal.genre === "Horror" ||
  //     peliculaOriginal.genre === "Thriller"
  //   ) {
  //     movie.paraAdultos = true;
  //   } else {
  //     movie.paraAdultos = false;
  //   }
});
